"""drop created_at

Revision ID: 3d000d89544c
Revises: 070220e3ca99
Create Date: 2024-04-22 17:11:02.307942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d000d89544c'
down_revision: Union[str, None] = '070220e3ca99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
